### PR TITLE
Use float instead of int to use the full precision SkiaSharp offers

### LINKED ISSUE #7: Integers are used instead of floating point values
* I would suggest to use SKRectangle instead of Rectangle
* Use `float maxLineWidth` for all `MeasureText` overloads

I would be happy to submit a PR containing these changes.

### PR DESCRIPTION
**Pull request by thisisthekap**
### Description

Fixes #7.

### Changes

**Use `SkiaSharp` types instead of `System.Drawing` types**

* Using `SKRect` instead of `Rectangle`
* Using `SKSize` instead of `Size`

**Fixed `MeasureText` overload**
* Using `float` instead of `int` for `maxLineWidth`

### Tests

* Tests in `SkiaTextRenderer.UnitTest` are passing
* Test output of `SkiaTextRenderer.Test` was compared visually with no differences noticed by me

### CODE REVIEW

**Comment by thisisthekap** [comment]
Just thought about backward compatiblity. As this library is already >= 1.0.0, we either should keep the API stable, or introduce version 2.0.0 with breaking changes.

Keeping the API stable would be achievable by creating method overloads to comply with the method signatures of the "old ones".

As [nuget.org](https://www.nuget.org/packages/SkiaTextRenderer/) shows download counts of about 50 per release, I would suggest to go for version 2.0.0 with breaking changes.

@ryancheung What are your thoughts about this?

**Comment by ryancheung** [comment]
@thisisthekap  Cann't agree with you anymore, since this lib may has somes user already according to the nuget downloads. We should add overloads for backward compability.

**Comment by thisisthekap** [comment]
@ryancheung How should we continue with methods returning e.g. `SKSize` instead of `Size`?

The only feasible options for this case would imho be:
1. Rename the new methods (unfortunately no good naming comes to my mind, maybe something like 'PreciseMeastureText' or `MeasureTextPrecisely` would be an option)
2. Create a separate class `TextRendererV2` containing the new implementations (I know that the name is bad, suggestions are welcome)

**Comment by thisisthekap** [comment]
Also using `System.Drawing.RectangleF` and `System.Drawing.SizeF` is not a feasible option, because `Size s = new SizeF()` is not valid (which we would need to solve the return type issue).

**Comment by ryancheung** [comment]
Yeah, the return type is an issue, we cannot avoid create method with new name.

**Comment by ryancheung** [comment]
Maybe a new TextRenderer should be introduced? like `TextRendererSK`

**Comment by ryancheung** [comment]
Would `System.Drawing` be an issue in mobile platform? AFAIK, it's not included in xamarin.ios and xamarin.android.
If this is an issue, we should break the backward compability rule. Since we need this  lib totally cross-platform.

**Comment by thisisthekap** [comment]
@ryancheung There were several issues concerning `System.Drawing` in the past, and I thing not all of them are already resolved. But to my knowledge, basic types like `Rectangle` and `Size` should be usable without any issue.

Several basic types, including the used ones, are [included in .net standard 2.0](https://docs.microsoft.com/en-us/dotnet/api/system.drawing?view=netstandard-2.0).

But avoiding the use of quite big frameworks feels good anyways. 😃

How should we proceed:
1. Create version 2.0.0 while dropping the old method signatures
2. Create version 2.0.0 while introducing `TextRendererSk`, making `TextRenderer` obsolete, and remove `TextRenderer` later in 2.1.0

**Comment by ryancheung** [comment]
How about bump version to 2.0 and rename TextRenderer to TextRendererOld, and then put new API in TextRenderer?

**Comment by ryancheung** [comment]
If someone want to stick with the System Drawing version they just need rename the class.

**Comment by thisisthekap** [comment]
Fine to me, but breaks the code of all the folks out there. If breaking the code is a feasible option, we could just modify the method signatures.

**Comment by ryancheung** [comment]
OK, I prefer your option 2, it should be more feasible and not make folks unhappy..

**Comment by thisisthekap** [comment]
@ryancheung Reintroduced the legacy methods to maintain backward compatibility.

**Comment by ryancheung** [comment]
@thisisthekap Thanks, merged.

**Pull request merged**
